version: 2

sources:
  - name: glamira_source
    database: "{{ env_var('DBT_SOURCE_PROJECT', target.project) }}"
    schema: "{{ env_var('DBT_SOURCE_SCHEMA', 'glamira_raw') }}"
    tables:
      - name: product_info
      - name: ip_location
      - name: summary19 #all data from 2019
      - name: raw_exchange_rates